kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4567
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: hack-chat-frontend:frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4567
